### ISSUE TITLE
Bug: ECDC's data has changed

### ISSUE THREAD

**Issue by raymas** [krusty-is-cool/Covid-Dashboard#14]
The first dataset is now broken: no plot are displayed

## Current behavior

- [X] [static-dashboard.js@68](https://github.com/krusty-is-cool/Covid-Dashboard/blob/7b606e6d9e44d01b15c83f591458dddf4032aa10/coviddashapp/static-dashboard.js#L68) requests data from https://opendata.ecdc.europa.eu/covid19/casedistribution/csv via CORS anywhere.
- [X] [static-dashboard.js@675](https://github.com/krusty-is-cool/Covid-Dashboard/blob/7b606e6d9e44d01b15c83f591458dddf4032aa10/coviddashapp/static-dashboard.js#L675) parse data returning an array of objects.
- [ ] [static-dashboard.js@398](https://github.com/krusty-is-cool/Covid-Dashboard/blob/7b606e6d9e44d01b15c83f591458dddf4032aa10/coviddashapp/static-dashboard.js#L398) parse data to a *plotly compatible* format.

This last step produces an error about undefined cases variable : 
```
Uncaught TypeError: cases is undefined
    updateNumbers https://www.coviddash.app/static-dashboard.js:423
    plotGraph https://www.coviddash.app/static-dashboard.js:844
    <anonymous> https://www.coviddash.app/static-dashboard.js:84
    send https://cdn.plot.ly/plotly-latest.min.js:20
    n https://cdn.plot.ly/plotly-latest.min.js:20
    f https://cdn.plot.ly/plotly-latest.min.js:20
static-dashboard.js:423:9
```

## Workaround

Commit [6aed3ac491af18b0af81a5b1ca2929d252cc5e45](https://github.com/krusty-is-cool/Covid-Dashboard/commit/6aed3ac491af18b0af81a5b1ca2929d252cc5e45) add a banner for this issue.

## Causes
As explained by the above commit:

The [ecdc daily number of new cases reported](https://opendata.ecdc.europa.eu/covid19/casedistribution/csv) has shifted to a **weekly** data collection since the 14th of decembre ([source](https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide)).

```The downloadable data file contains information on the 14-day notification rate of newly reported COVID-19 cases per 100 000 population and the 14-day notification rate of reported deaths per million population by week and country. Each row contains the corresponding data for a certain day and per country. The file is updated weekly. You may use the data in line with ECDC’s copyright policy.```

## Possible solution

Delete the ecdc choice from the dashboard.

**Comment by raymas** [comment]
@krusty-is-cool what are your plans on this?

**Comment by krusty-is-cool** [comment]
Thank you @raymas for openning this issue.

As you saw, I quickly added an alert banner to inform user. This is highly temporary.

## Step 1

- [x] Remove ECDC dataset choice and set Johns Hopkins University CSSE as the default dataset.

## Step 2

- [x] **Major update for the app's back-end.**
Key features: 
- being able to trigger alerts and notifications from the VM instead of having to commit changes on Github 
- notifying the service worker when a new version of the dashboard is available so it could renew the cache. I expect it helps with issue #10 

## Step 3

- [ ] Wait the next update of ECDC dataset to evaluate the relevance of displaying a weekly updated dataset and bringing back ECDC dataset.

**Comment by krusty-is-cool** [comment]
Commit d2ff24518dbb78a4cc76e399320091586f6534f6 accomplishes Step 1 of fix.
